# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: MinimalWaste
subtitle: Minimalismus und Zero Waste
email: dienste@minimalwaste.de
description: >- # this means to ignore newlines until "baseurl:"
  Schön, dass du hier bist! Ich bin Sarah und auf MinimalWaste schreibe ich über Minimalismus, Zero Waste und
  gebe Tipps zu weniger Konsum und mehr Nachhaltigkeit.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://minimalwaste.de" # the base hostname & protocol for your site, e.g. http://example.com
keywords: [minimalismus, zero waste]
permalink: /blog/:title
affiliate-hint: "* Dieser Beitrag enthält Affiliate-Links. Dadurch kann ich über Produkte
                und Dienste, die ich gerne Nutze, etwas verdienen ohne dass du mehr bezahlen musst."

# Social
facebook-link: https://www.facebook.com/MinimalWasteBlog/
instagram-link: https://www.instagram.com/minimalwaste.de/
twitter-link: https://twitter.com/MinimalWaste
pinterest-link: https://www.pinterest.de/minimalwaste/
patreon-link: https://www.patreon.com/minimalwaste
email-website: info@minimalwaste.de
twitter-username: MinimalWaste

# Authors
sarah-lettmann:
  name: Sarah Lettmann
  bio: Hi, ich bin Sarah. Hier auf MinimalWaste schreibe ich über Zero Waste und Minimalismus
        und gebe Tipps wie man sein Leben nachhaltiger gestalten kann.
  picture: /assets/authors/sarahlettmann.jpg
  more-page: /author/sarah-lettmann

# Images
defaults:
  - scope:
      path: "assets/gallery"
    values:
      gallery: true

# Build settings
future: false
markdown: kramdown
theme:
plugins:
  #- jekyll-feed

# Sass
sass:
  style: compressed

# agent
web-dev: Sarah Lettmann
web-dev-site: https://twitter.com/SarahLettmann

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
