# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: MinimalWaste
subtitle: Minimalismus und Zero Waste
email: info@minimalwaste.de
description: >- # this means to ignore newlines until "baseurl:"
  Auf MinimalWaste gibt Tipps und Erfahrungsberichte rund um Zero Waste,
  Minimalismus, Fair Fashion und Nachhaltigkeit.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://minimalwaste.de" # the base hostname & protocol for yur site, e.g. http://example.com
keywords: [minimalismus, zero waste]
permalink: /blog/:title/
pagelinks-posts: ["0073", "0005", "0018"]
featured-posts: ["0084", "0064", "0049", "0051", "0042"]
start-zero-waste: ["0084", "0083", "0044", "0062", "0073", "0037"]
aspects-sustainability: ["0059", "0075", "0042", "0067", "0077", "0068"]
featured-pages:
  - title: Alle Unverpack Läden im Überblick
    href: /blog/unverpackt-einkaufen-alle-laeden/
    image: /assets/title-images/2016/2016-11-21-unverpackt-einkaufen-alle-laeden.jpg
  - title: Nachhaltige und Plastikfreie Online Shops
    href: /blog/plastikfrei-einkaufen-alle-onlineshops/
    image: /assets/title-images/2017/2017-09-17-plastikfrei-einkaufen-alle-onlineshops.jpg

# Social
facebook-link: https://www.facebook.com/MinimalWasteBlog/
instagram-link: https://www.instagram.com/minimalwaste.de/
twitter-link: https://twitter.com/MinimalWaste
pinterest-link: https://www.pinterest.de/minimalwaste/
youtube-link: https://www.youtube.com/channel/UCpVAerr1RGJBHBOL_8-TsnQ/
patreon-link: https://www.patreon.com/bePatron?u=10143948
email-website: info@minimalwaste.de
twitter-username: MinimalWaste

# Authors
sarah-lettmann:
  name: Sarah Lettmann
  bio: Hi, ich bin Sarah. Hier auf MinimalWaste schreibe ich über Zero Waste und Minimalismus
        und gebe Tipps wie man sein Leben nachhaltiger gestalten kann.
  picture: /assets/authors/sarahlettmann.jpg

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      author: "sarah-lettmann"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "newsletter" # previously `post` in Jekyll 2.2.
    values:
      layout: "newsletter"

# Build settings
future: false
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  #- jekyll-feed
  - jekyll-target-blank

collections:
  newsletter:
    output: true
    permalink: /newsletter/:title/

# Sass
sass:
  style: compressed

# agent
web-dev: Sarah Lettmann
web-dev-site: https://twitter.com/SarahLettmann

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

theme: jekyll-theme-minimal
